hngi/Car-Park-App-Web

- car-park-users.html
1. Worked on the responsiveness on Users Page
**URL: http://teamgravity.africa/mary_works/car-park-users.html#**
> Mary_Jonah worked on responsiveness

- desktop11.html
https://nkeenendu.github.io/desk/
created by @emmysoft and @nelyne
> desktop 11 page with new navbar

- index.html
Test URL: https://praiseey.github.io/Car_Park_App_Web/
> Desktop 10

- admin-analytics.html
I worked on the Admin-Analytics Page. @Kai made it responsive. This is the test url - https://silly-villani-2ecb34.netlify.com.... Please, feedback is highly appreciated
> Admin-Analytics Page

- desktop11,.html
https://nkeenendu.github.io/desk/
that is the test repo
> we added the desktop11 page

- nav.html
Url: https://benjamin-bala.github.io/Car-Park-App-Web/
commit : https://github.com/benjamin-bala/Car-Park-App-Web/commits/test-branch
> Created Reusable Navbar

- admin-analytics.html
PLEASE, KINDLY IGNORE THE TWO I PREVIOUSLY SENT. I HAVE MADE THE EXPECTED CORRECTIONS IN THE LINKS.......I have corrected the links on the page; This is the url to confirm: https://musing-morse-742983.netlify.com
> LINKED PAGE

- css/Desktop5.css
- demographics.html
- js/desktop5.js
https://omoruyis.github.io/start2/
> adding-links for demographic section

- desktop11,.html
linked pages created by nelyne
> linked sidebar and others in desktop 11

- car-park-users.html
1. Added references to links
URL: **http://teamgravity.africa/car-park/car-park-users.html**
> Mary_Jonah, Added links to User Page 

- css/Desktop5.css
- demographics.html
https://omoruyis.github.io/start2/
> sidebar for mobile view for dashboard demographic page

- addpark.html
Test URL:
https://afolwalex.github.io/addpark.html
> a new add a car park feature

- support.css
- support.html
Test url https://favour-chibueze.github.io/Car-Park-App2/
> I worked on support page

- css/Desktop5.css
- demographics.html
> fixing-bugs for dashboard demographic page

- settings_account.html
- Did a proper alignment for the username on the account settings page
- Redesigned the search box
> Updated account settings page

- notification.html
Test link: https://ndkkqueenie.github.io/notify-page/notification.html
> Create notification.html page

- mailSupport.html
fatimah019.github.io
Test link
> MailSupport done

- add-car-parks.html
- carpark_manage_addcar.html
achievement-rates-tracker.000webhostapp.com
Test link
I have named correctly
> Fe   admin pages

- manageparks.html
Reworked on the page after errors were received
> manageparks.html

- mail_mailcampaign.html
https://cramwordplay.github.io/mailCampaign/
> mail_mailcampaign.html

- carpark_manage.html
- carpark_status.html
- css/carpark_manage.css
- css/carpark_status.css
i created the manage car parks and car parks status pages
> Manage Parks pages

- dashboard_carpark.html
- dashboard_existingusers.html
- dashboard_issues.html
- dashboard_newusers.html
the overview pages made are: issues, users, existing users and carpark
test url:
issues page: https://taofeeqcarpark.000webhostapp.com/dashboard_issues
new users page: https://taofeeqcarpark.000webhostapp.com/dashboard_newusers.html
existing users page: https://taofeeqcarpark.000webhostapp.com/dashboard_existingusers.html
car page page: https://taofeeqcarpark.000webhostapp.com/dashboard_carpark.html
> Made the dashboard overview pages: issues, users, e.t.c.

- notification.html
Updated notification.html page with popup message. Test link:  https://ndkkqueenie.github.io/notify-page/notification.html
> Updated notification.html page

- demographics.html
links to some pages were broken, i fixed the broken links
> renaming-links

- dashboard_carpark.html
Edited Carpack_Dashboard Page to highlight the various parking locations
> Dashboard_Carpack Page

- dashboard_existingusers.html
Added a marker for the various parking location in the map
> Dashboard_Existing users Page

- dashboard_issues.html
Added a Parking Marker to the various locations in the Dashboard_issues page
> Dashboard_issues page

- carpark_manage.html
- carpark_status.html
Fixed some minor bugs in the navbar
> Bugs fixing

- css/Desktop5.css
- dashboard_demographics.html
- js/desktop5.js
i added the a dashboard_demographics.html page to the branch
> adding-demographics-page

- carpark_manage.html
- carpark_manage_addcar.html
- carpark_status.html
- css/carpark_manage.css
- css/carpark_status.css
i made the manage carparks pages
> adding-manage-carparks

- carpark_manage.html
- carpark_manage_addcar.html
- carpark_status.html
- css/Desktop5.css
- demographics.html
- js/desktop5.js
i changed the sidebar for the manage car parks pages
> changing-sidebar

- index.html
- signup.html
Created the login and  sign up pages for the admin
> index.html/sign up.html

- index.html
- signup.html
Made changes to the responsiveness on mobile view and also centralized the sign in/sign up boxes
> index.html/signup.html

- carpark_manage.html
- carpark_status.html
- demographics.html
I removed the "X" button from the pages i did
> Removing the "X" button 

- mail_supportdrafts.html
test url: https://taofeeqcarpark.000webhostapp.com/mail_supportinbox.html
> made the mail support inbox and draft page

- mail_supportsent.html
- mail_supportstarred.html
test url : https://beckyatule.github.io/Car-Park-App-Web/mail_supportsent.html
https://beckyatule.github.io/Car-Park-App-Web/mail_supportstarred.html
> Made the mail support sent and mail support starred pages

- css/mail_message.css
- mail_mailcampaigncompleted.html
- mail_message.html
i created the the mail-message page
> making-mail-message

- mail_supportdrafts.html
- mail_supportinbox.html
- mail_supportsent.html
- mail_supportstarred.html
it was added to the inbox, starred, sent and drafts pages for mail support
test url: https://taofeeqcarpark.000webhostapp.com/mail_supportinbox.html
> added notification popup to mail support pages

- mail_supportdrafts.html
- mail_supportinbox.html
- mail_supportsent.html
- mail_supportstarred.html
test url:  https://taofeeqcarpark.000webhostapp.com/mail_supportinbox.html
> linked the mail support pages
